# 101 Pandas Exercises for Data Analysis

In [1]:
# 1.How to import pandas and check the version?
import pandas as pd
import numpy as np

In [13]:
pd.__version__

'3.0.5'

In [46]:
# 2.How to create a series from a list, numpy array and dict
# Create a pandas series from each of the items below: a list, numpy and a dictionary
mylist = list("abcdefghijklmnopqrstuvwxyz")
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [47]:
s1 = pd.Series(mylist)
pdlist.head()

0    a
1    b
2    c
3    d
4    e
dtype: str

In [48]:
s2 = pd.Series(myarr)
s2.tail()

21    21
22    22
23    23
24    24
25    25
dtype: int64

In [49]:
s3 = pd.Series(mydict)
s3.head(10)

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
i    8
j    9
dtype: int64

In [50]:
# 3.How to convert the index of a series into a column of a dataframe?
# Convert the series ser into a dataframe with its index as another column on the dataframe
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
ser.head()

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [51]:
df = ser.to_frame().reset_index()
df.head()

  index  0
0     a  0
1     b  1
2     c  2
3     d  3
4     e  4

In [52]:
# 4.How to combine many series to form a dataframe?
# Combine ser1 and ser2 to form a dataframe
ser1 = pd.Series(list("abcedfghijklmnopqrstuvwxyz"))
ser2 = pd.Series(np.arange(26))

In [53]:
df = pd.concat([ser1, ser2], axis=1)
df.columns =["col1", "col2"]
df.head()

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [54]:
# the other Solutions
df2= pd.DataFrame({"col1": ser1, "col2": ser2})
df2.head()

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [55]:
# 5.How to assign name to the series' index?
# Give a name to the series ser calling it 'alphabets'
ser = pd.Series(list("abcedfghijklmnopqrstuvwxyz"))

In [56]:
ser.name = "alpahebets"
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alpahebets, dtype: str

In [5]:
# 6.How to get the items of series A not present in series B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [6]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [7]:
# 7.How to get the items not common to both series A and series B?
set(ser1)

{1, 2, 3, 4, 5}

In [8]:
set(ser2)

{4, 5, 6, 7, 8}

In [9]:
set(ser1) ^ set(ser2)

{1, 2, 3, 6, 7, 8}

In [15]:
x = list(set(ser1) ^ set(ser2))
type(x)

list

In [16]:
pd.Series(x)

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64

In [22]:
# Solution
ser_u = pd.Series(np.union1d(ser1, ser2)) # union
ser_i = pd.Series(np.intersect1d(ser1, ser2)) # intersect
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [27]:
# 8.How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
ser = pd.Series(np.random.normal(10, 5, 25))
ser.head()

0    -0.060540
1    10.280742
2    18.282375
3     7.323646
4    10.865861
dtype: float64

In [33]:
np.percentile(ser, q=[0, 25, 50, 75, 100])

array([-0.06053994,  8.26876179, 10.02813902, 13.75046196, 19.17387561])

In [35]:
# 9.How to get frequency counts of unique items of a series?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.head()

0    h
1    g
2    g
3    f
4    b
dtype: str

In [36]:
ser.value_counts()

b    9
f    5
d    5
g    3
e    3
c    2
a    2
h    1
Name: count, dtype: int64

In [38]:
# 10.How to keep only top 2 most frequent values as it is and replace everything else as "Other"?
np.random.seed(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
ser.head()

0    1
1    1
2    4
3    4
4    4
dtype: int64

In [108]:
type(ser)

pandas.Series

In [118]:
ser = ser.astype('object')
ser.dtype

dtype('O')

In [119]:
top_two = ser.value_counts().index[:2]
top_two

Index([1, 4], dtype='object')

In [120]:
ser[~ser.isin(top_two)] = "Other"
ser

0         1
1         1
2         4
3         4
4         4
5         4
6         1
7     Other
8     Other
9         1
10    Other
11    Other
dtype: object