# 101 Pandas Exercises for Data Analysis

In [57]:
# 1.How to import pandas and check the version?
import pandas as pd
import numpy as np

In [13]:
pd.__version__

'3.0.5'

In [46]:
# 2.How to create a series from a list, numpy array and dict
# Create a pandas series from each of the items below: a list, numpy and a dictionary
mylist = list("abcdefghijklmnopqrstuvwxyz")
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [47]:
s1 = pd.Series(mylist)
pdlist.head()

0    a
1    b
2    c
3    d
4    e
dtype: str

In [48]:
s2 = pd.Series(myarr)
s2.tail()

21    21
22    22
23    23
24    24
25    25
dtype: int64

In [49]:
s3 = pd.Series(mydict)
s3.head(10)

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
i    8
j    9
dtype: int64

In [50]:
# 3.How to convert the index of a series into a column of a dataframe?
# Convert the series ser into a dataframe with its index as another column on the dataframe
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
ser.head()

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [51]:
df = ser.to_frame().reset_index()
df.head()

  index  0
0     a  0
1     b  1
2     c  2
3     d  3
4     e  4

In [52]:
# 4.How to combine many series to form a dataframe?
# Combine ser1 and ser2 to form a dataframe
ser1 = pd.Series(list("abcedfghijklmnopqrstuvwxyz"))
ser2 = pd.Series(np.arange(26))

In [53]:
df = pd.concat([ser1, ser2], axis=1)
df.columns =["col1", "col2"]
df.head()

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [54]:
# the other Solutions
df2= pd.DataFrame({"col1": ser1, "col2": ser2})
df2.head()

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [55]:
# 5.How to assign name to the series' index?
# Give a name to the series ser calling it 'alphabets'
ser = pd.Series(list("abcedfghijklmnopqrstuvwxyz"))

In [56]:
ser.name = "alpahebets"
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alpahebets, dtype: str